### ISSUE TITLE
Freeradius 2 linelog accounting configuration

### ISSUE THREAD

**Issue by olschneider** [jothoma1/graylog-contentpack-freeradius#1]
Hello,

First, thanks for this contentpack, it's very useful.
I can't make linelog accounting work. Do you have any informations about this ?
I know this is not an issue but i don't find help.

Thanks

Regards,

**Comment by jothoma1** [comment]
Hello,

Thanks for your message !
You just have to : 
1) edit the file /etc/raddb/mods-available/linelog 
2) make a symlink in mods-enabled
3) restart freeradius

Do you use freeradius 3 or 2 ? i have only tried with 3
Regards

**Comment by olschneider** [comment]
Hello Johan,

It works for me now.

Many thanks.

I use freeradius v3 only.

Regards,

----- Mail original -----
De: "Johan THOMAS" notifications@github.com
À: "jothoma1/graylog-contentpack-freeradius" graylog-contentpack-freeradius@noreply.github.com
Cc: "olschneider" olschneider@free.fr, "Author" author@noreply.github.com
Envoyé: Mercredi 20 Juillet 2016 17:48:18
Objet: Re: [jothoma1/graylog-contentpack-freeradius] Freeradius 2 linelog accounting configuration (#1)

Hello, 

Thanks for your message ! 
You just have to : 
1) edit the file /etc/raddb/mods-available/linelog 
2) make a symlink in mods-enabled 
3) restart freeradius 

Do you use freeradius 3 or 2 ? i have only tried with 3 
Regards

**Comment by jothoma1** [comment]
Nice to see it works for you now !
Regards
